env:
  ML_REPO_NAME: <paste ml-repo name here>
name: diabetes-train-job
type: job
image:
  type: build
  build_spec:
    type: tfy-python-buildpack
    command: python train.py --kernel {{kernel}} --n_quantiles {{n_quantiles}}
    python_version: '3.9'
    requirements_path: requirements.txt
    build_context_path: ./
  build_source:
    type: local
params:
  - name: n_quantiles
    default: '100'
  - name: kernel
    default: linear
    description: kernel for svm
retries: 0
trigger:
  type: manual
resources:
  cpu_limit: 0.5
  cpu_request: 0.2
  memory_limit: 500
  memory_request: 200
  ephemeral_storage_limit: 2000
  ephemeral_storage_request: 1000
