name: churn-prediction-train
type: job
env:
  TFY_API_KEY: # enter your api key here
image:
  type: build
  build_spec:
    type: tfy-python-buildpack
    command: >-
      python main.py --n_neighbors {{n_neighbors}} --weights {{weights}}
      --algorithm {{algorithm}} --power {{power}}
    python_version: '3.9'
    build_context_path: ./
  build_source:
    type: local
params:
  - name: n_neighbors
    default: '5'
    description: Number of neighbors to use by default
  - name: weights
    default: uniform
    description: 'Weight function used in prediction.  Possible values: uniform, distance'
  - name: algorithm
    default: auto
    description: >-
      Algorithm used to compute the nearest neighbors: possible values: 'auto',
      'ball_tree', 'kd_tree', 'brute'
  - name: power
    default: '2'
    description: >-
      Power parameter for the Minkowski metric. When p = 1, this is
      manhattan_dist, and euclidean_dist p = 2
restart: Never
retries: 1
timeout: 1000
trigger:
  type: manual
resources:
  cpu_limit: 1
  cpu_request: 1
  memory_limit: 2000
  memory_request: 2000
  ephemeral_storage_limit: 2000
  ephemeral_storage_request: 1000
failed_jobs_history_limit: 20
successful_jobs_history_limit: 20