# Replace `<YOUR_SECRET_FQN>`, with the actual values.
name: iris-train-job
components:
- name: iris-train-job
  type: job
  image:
    type: build
    build_source:
      type: local
    build_spec:
      type: tfy-python-buildpack
      command: python train.py
      requirements_path: requirements.txt
  env:
  - name: MLF_API_KEY
    value: tfy-secret://<YOUR_SECRET_FQN>
